# Generated by Django 2.2.7 on 2020-09-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='like',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
