# Generated by Django 2.2.7 on 2020-06-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prof_pic',
            field=models.ImageField(default='default.jpg', upload_to='prof_pic'),
        ),
    ]
